### ISSUE TITLE
Stop using FormData

### ISSUE THREAD

**Issue by RDegnen** [ga-wdi-boston/js-xml-http-request#3]
@gaand

**Comment by gaand** [comment]
FormData should only be used when uploading files (Content-Type: multipart/form-data).  In that case, it is required.

**Comment by jrhorn424** [comment]
@gaand I believe this was missed by GitHub from your commit message. Ready to close?

**Comment by gaand** [comment]
There is still an open pull request.  I'm happy to merge, but it's my pull request.
